# Generated by Django 3.0.6 on 2020-06-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
