# Generated by Django 3.0.6 on 2020-06-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.Album'),
        ),
    ]
