# Generated by Django 3.0.6 on 2020-06-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_auto_20200602_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
